apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:
    repoURL: "https://github.com/arctic-gsu/deployKF/deploy"
    targetRevision: "main"
    path: "GENERATOR_OUTPUT/argocd"
  destination:
    server: "https://10.245.19.201:6443"
    namespace: "argocd"