
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-pipelines--backend-object-store-auth
  namespace: kubeflow
data:
  access_key: "MHlwUUszWk1pOXFDN1YzMw=="
  secret_key: "S2s0UERhUkM0ek04NHdOOWN2eFFUYWtNZlZlTkN2YTU="