########################################
## SHARED | deploykf-helpers
########################################
deployKF_helpers:
  deploykf_profiles:
    users_id_mapping: {"chris":{"email":"cchildress@gsu.edu","id":"chris"},"neranjan":{"email":"neranjan@gsu.edu","id":"neranjan"},"sanju":{"email":"stimsina@gsu.edu","id":"sanju"},"shruti":{"email":"sshrestha8@gsu.edu","id":"shruti"},"user-1":{"email":"user1@example.com","id":"user-1"},"user-2":{"email":"user2@example.com","id":"user-2"}}
    profiles_users_access_mapping: {"team-1":{"chris":{"notebooksAccess":true,"role":"edit"},"neranjan":{"notebooksAccess":true,"role":"edit"},"sanju":{"notebooksAccess":true,"role":"edit"},"shruti":{"notebooksAccess":true,"role":"edit"},"user-1":{"notebooksAccess":true,"role":"edit"},"user-2":{"notebooksAccess":true,"role":"edit"}},"team-1-prod":{"chris":{"notebooksAccess":false,"role":"view"},"neranjan":{"notebooksAccess":false,"role":"view"},"sanju":{"notebooksAccess":false,"role":"view"},"shruti":{"notebooksAccess":false,"role":"view"},"user-1":{"notebooksAccess":false,"role":"view"},"user-2":{"notebooksAccess":false,"role":"view"}}}
    users_profiles_access_mapping: {"chris":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"}},"neranjan":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"}},"sanju":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"}},"shruti":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"}},"user-1":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"}},"user-2":{"team-1":{"notebooksAccess":true,"role":"edit"},"team-1-prod":{"notebooksAccess":false,"role":"view"}}}

  kubeflow:
    pipelines:
      object_store:
        profile:
          cloned_secret_name: "cloned--pipelines-object-store-auth"
          generated_access_key_key: "AWS_ACCESS_KEY_ID"
          generated_secret_key_key: "AWS_SECRET_ACCESS_KEY"


########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:

  clusterDomain: cluster.local

  minio:
    namespace: "deploykf-minio"

  argoWorkflows:
    enabled: true
    namespace: "kubeflow-argo-workflows"

  kubeflow:
    useridHeader: kubeflow-userid

    pipelines:
      enabled: true
      namespace: kubeflow
      pipelineUI:
        namespace: kubeflow
        serviceAccount: ml-pipeline-ui
      objectStore:
        useExternal: true
        auth:
          fromEnv: true

  gateway:
    namespace: "deploykf-istio-gateway"
    serviceAccount: "deploykf-gateway"
    emailToLowercase: false


########################################
## CONFIGS | profiles
########################################

## profile defaults
##
profileDefaults:

  ## a common prefix to add to all profile names
  ##
  profileNamePrefix: ""

  ## the default email to set as the owner of profiles
  ##
  ownerEmail: "admin@example.com"

  ## the default access for members of profiles, when not explicitly specified
  ##
  memberAccess:

    ## the Kubernetes RBAC role to bind to users in the profile namespace
    ##  - "edit": binds "ClusterRole/kubeflow-edit" (can view/create/delete resources)
    ##  - "view": binds "ClusterRole/kubeflow-view" (cam view resources)
    ##
    role: "view"

    ## if the user can ~connect~ to kubeflow notebooks in the profile
    ##
    notebooksAccess: false

  ## the default list of plugins for profiles, when not explicitly specified
  ##
  plugins: [{"kind":"keycloak-gatekeeper","spec":{"configExistingSecret":"my-dex-plugins-secret","configExistingSecretKey":"SecretKey"}}]

  ## the default resource quota for profiles, when not explicitly specified
  ##  - spec for ResourceQuotaSpec:
  ##    https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#resourcequotaspec-v1-core
  ##
  resourceQuotaSpec: {}

  ## the default tool configs for profiles
  ##
  tools:

    ## the default Kubeflow Pipelines configs for profiles
    ##
    kubeflowPipelines:

      ## the default Kubeflow Pipelines object store auth configs for profiles
      ##
      objectStoreAuth:
        existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
        existingSecretNamespace: "kubeflow"
        existingSecretAccessKeyKey: "AWS_ACCESS_KEY_ID"
        existingSecretSecretKeyKey: "AWS_SECRET_ACCESS_KEY"

## user entities
##  - a list of users that can be referenced when defining profile members
##
users: [{"email":"user1@example.com","id":"user-1"},{"email":"user2@example.com","id":"user-2"},{"email":"neranjan@gsu.edu","id":"neranjan"},{"email":"cchildress@gsu.edu","id":"chris"},{"email":"stimsina@gsu.edu","id":"sanju"},{"email":"sshrestha8@gsu.edu","id":"shruti"}]

## group entities
##  - a list of groups that can be referenced when defining profile members
##
groups: [{"id":"team-1","users":["user-1","user-2","neranjan","chris","sanju","shruti"]}]

## profile definitions
##  - a list of profile definitions to be generated
##
profiles: [{"members":[{"access":{"notebooksAccess":true,"role":"edit"},"group":"team-1"}],"name":"team-1"},{"members":[{"access":{"notebooksAccess":false,"role":"view"},"group":"team-1"}],"name":"team-1-prod"}]
