########################################
## SHARED | deploykf-helpers
########################################
deployKF_helpers:
  deploykf_profiles:
    users_id_mapping: {"cchildress":{"email":"cchildress@gsu.edu","id":"cchildress"},"neranjan":{"email":"neranjan@gsu.edu","id":"neranjan"},"sshrestha8":{"email":"sshrestha8@gsu.edu","id":"sshrestha8"},"stimsina":{"email":"stimsina@gsu.edu","id":"stimsina"}}
    profiles_users_access_mapping: {"team-1":{"cchildress":{"notebooksAccess":true,"role":"edit"},"neranjan":{"notebooksAccess":true,"role":"edit"},"sshrestha8":{"notebooksAccess":true,"role":"edit"},"stimsina":{"notebooksAccess":true,"role":"edit"}}}
    users_profiles_access_mapping: {"cchildress":{"team-1":{"notebooksAccess":true,"role":"edit"}},"neranjan":{"team-1":{"notebooksAccess":true,"role":"edit"}},"sshrestha8":{"team-1":{"notebooksAccess":true,"role":"edit"}},"stimsina":{"team-1":{"notebooksAccess":true,"role":"edit"}}}

  kubeflow:
    pipelines:
      object_store:
        profile:
          cloned_secret_name: "cloned--pipelines-object-store-auth"
          generated_access_key_key: "access_key"
          generated_secret_key_key: "secret_key"


########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:

  clusterDomain: cluster.local

  minio:
    namespace: "deploykf-minio"

  argoWorkflows:
    enabled: true
    namespace: "kubeflow-argo-workflows"

  kubeflow:
    useridHeader: kubeflow-userid

    pipelines:
      enabled: true
      namespace: kubeflow
      pipelineUI:
        namespace: kubeflow
        serviceAccount: ml-pipeline-ui
      objectStore:
        useExternal: true
        auth:
          fromEnv: true

  gateway:
    namespace: "deploykf-istio-gateway"
    serviceAccount: "deploykf-gateway"
    emailToLowercase: false


########################################
## CONFIGS | profiles
########################################

## profile defaults
##
profileDefaults:

  ## a common prefix to add to all profile names
  ##
  profileNamePrefix: ""

  ## the default email to set as the owner of profiles
  ##
  ownerEmail: "admin@example.com"

  ## the default access for members of profiles, when not explicitly specified
  ##
  memberAccess:

    ## the Kubernetes RBAC role to bind to users in the profile namespace
    ##  - "edit": binds "ClusterRole/kubeflow-edit" (can view/create/delete resources)
    ##  - "view": binds "ClusterRole/kubeflow-view" (cam view resources)
    ##
    role: "view"

    ## if the user can ~connect~ to kubeflow notebooks in the profile
    ##
    notebooksAccess: false

  ## the default list of plugins for profiles, when not explicitly specified
  ##
  plugins: [{"kind":"keycloak-gatekeeper","spec":{"configExistingSecret":"my-dex-plugins-secret","configExistingSecretKey":"SecretKey"}}]

  ## the default resource quota for profiles, when not explicitly specified
  ##  - spec for ResourceQuotaSpec:
  ##    https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#resourcequotaspec-v1-core
  ##
  resourceQuotaSpec: {}

  ## the default tool configs for profiles
  ##
  tools:

    ## the default Kubeflow Pipelines configs for profiles
    ##
    kubeflowPipelines:

      ## the default Kubeflow Pipelines object store auth configs for profiles
      ##
      objectStoreAuth:
        existingSecret: "kubeflow-pipelines--profile-object-store-auth--{profile_name}"
        existingSecretNamespace: ""
        existingSecretAccessKeyKey: "access_key"
        existingSecretSecretKeyKey: "secret_key"

## user entities
##  - a list of users that can be referenced when defining profile members
##
users: [{"email":"neranjan@gsu.edu","id":"neranjan"},{"email":"cchildress@gsu.edu","id":"cchildress"},{"email":"stimsina@gsu.edu","id":"stimsina"},{"email":"sshrestha8@gsu.edu","id":"sshrestha8"}]

## group entities
##  - a list of groups that can be referenced when defining profile members
##
groups: [{"id":"team-1--users","users":["neranjan","cchildress","stimsina","sshrestha8"]}]

## profile definitions
##  - a list of profile definitions to be generated
##
profiles: [{"members":[{"access":{"notebooksAccess":true,"role":"edit"},"group":"team-1--users"}],"name":"team-1"}]
