apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--poddefaults-webhook
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: poddefaults-webhook
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: deploykf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/arctic-gsu/deployKF/"
    targetRevision: "main"
    path: "GENERATOR_OUTPUT/manifests/kubeflow-tools/poddefaults-webhook"
  destination:
    server: "https://10.245.19.201:6443"
    namespace: kubeflow
  ignoreDifferences:
    ## `caBundle` is injected by cert-manager
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"

    ## `rules` are aggregated when `aggregationRule.clusterRoleSelectors` is set
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - "select(.aggregationRule.clusterRoleSelectors | length > 0) | .rules"