
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: kubeflow-katib--restart-on-secret-update--mysql
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
    - name: trigger-deployment-restarts
      match:
        any:
          - resources:
              kinds:
                - Secret
              names:
                - "katib-mysql-secret"
              namespaces:
                - "kubeflow"
              operations:
                - CREATE
                - UPDATE
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
            namespace: "{{ request.namespace }}"
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  deploykf.org/restart-trigger: "{{ random('[0-9a-z]{32}') }}"
              spec:
                containers:
                  - env:
                      - valueFrom:
                          secretKeyRef:
                            <(name): "{{ request.object.metadata.name }}"